config/routes.rb
Rails.application.routes.draw do
  resources :offers
    

#  resources :affiliates
    
       get "/affiliates", to:"affiliates#index",as: 'affiliates'

      post "/affiliates", to:"affiliates#create"
      get "/affiliates/new", to:"affiliates#new",as: 'new_affiliate'
      get "/affiliates/:id/:code/edit", to:"affiliates#edit",as: 'edit_affiliate'
     patch "/affiliates/:id/:code", to:"affiliates#update"
     get "/affiliates/:id/:code", to:"affiliates#show",as: 'affiliate'
    
     put "/affiliates/:id/:code", to:"affiliates#update"



 
  #   Prefix Verb   URI Pattern                    Controller#Action
#        offers GET    /offers(.:format)              offers#index
    #           POST   /offers(.:format)              offers#create
 #    new_offer GET    /offers/new(.:format)          offers#new
 #   edit_offer GET    /offers/:id/edit(.:format)     offers#edit
 #        offer GET    /offers/:id(.:format)          offers#show
  #             PATCH  /offers/:id(.:format)          offers#update
    #           PUT    /offers/:id(.:format)          offers#update
     #          DELETE /offers/:id(.:format)          offers#destroy
  #  affiliates GET    /affiliates(.:format)          affiliates#index
   #            POST   /affiliates(.:format)          affiliates#create
# new_affiliate GET    /affiliates/new(.:format)      affiliates#new
#edit_affiliate GET    /affiliates/:id/edit(.:format) affiliates#edit
  #   affiliate GET    /affiliates/:id(.:format)      affiliates#show
   #            PATCH  /affiliates/:id(.:format)      affiliates#update
    #           PUT    /affiliates/:id(.:format)      affiliates#update
    #           DELETE /affiliates/:id(.:format)      affiliates#destroy

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/affiliate.rb
class Affiliate < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
class Offer < ApplicationRecord
end

app/controllers/affiliates_controller.rb
class AffiliatesController < ApplicationController
  before_action :set_affiliate, only: [:show, :edit, :update, :destroy]
#  before_action :set_offers, only: [:show]    

  # GET /affiliates
  # GET /affiliates.json
  def index
    @affiliates = Affiliate.all
  end

  # GET /affiliates/1
  # GET /affiliates/1.json
  def show
      @offers = Offer.all
      @MyC = @offers.where(finalStatus:0)
      @aff=@affiliate.name
      @offers = Offer.where(ownerID:@affiliate.id)
      @M=0
      @text=""  
      @textSub=""
      @textS=""
      @MyC.each do |money|
      @M =money.revenue + @M
            
      end  
 
  end

  # GET /affiliates/new
  def new
    @affiliate = Affiliate.new
    @code = rand(999999999)  
  end

  # GET /affiliates/1/edit
  def edit
  end

  # POST /affiliates
  # POST /affiliates.json
  def create
    @affiliate = Affiliate.new(affiliate_params)

    respond_to do |format|
      if @affiliate.save
        format.html { redirect_to @affiliate, notice: 'Affiliate was successfully created.' }
        format.json { render :show, status: :created, location: @affiliate }
      else
        format.html { render :new }
        format.json { render json: @affiliate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /affiliates/1
  # PATCH/PUT /affiliates/1.json
  def update
    respond_to do |format|
      if @affiliate.update(affiliate_params)
        format.html { redirect_to @affiliate, notice: 'Affiliate was successfully updated.' }
        format.json { render :show, status: :ok, location: @affiliate }
      else
        format.html { render :edit }
        format.json { render json: @affiliate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /affiliates/1
  # DELETE /affiliates/1.json
  def destroy
    @affiliate.destroy
    respond_to do |format|
      format.html { redirect_to affiliates_url, notice: 'Affiliate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_affiliate
      @affiliate = Affiliate.find(params[:id,])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def affiliate_params
      params.require(:affiliate).permit(:name, :logoLink, :moneyConfirmed,:code)
    end
    def offers_params
      params.require(:offer).permit(:name, :ownerID, :installs, :revenue, :risk, :finalStatus, :comment1, :comment2)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.all
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)

    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:name, :ownerID, :installs, :revenue, :risk, :finalStatus, :comment1, :comment2, :subComent1, :subComent2)
    end
end

app/helpers/affiliates_helper.rb
module AffiliatesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/affiliates/_form.html.erb
<%= form_for(affiliate) do |f| %>
  <% if affiliate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(affiliate.errors.count, "error") %> prohibited this affiliate from being saved:</h2>

      <ul>
      <% affiliate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :logoLink %>
    <%= f.text_field :logoLink %>
  </div>

  <div class="field">
    <%= f.label :moneyConfirmed %>
    <%= f.text_field :moneyConfirmed %>
  </div>
  <div class="field">
    <%= f.label :code %>
    <%= f.text_field :code, :value => @code %>   
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/affiliates/edit.html.erb
<h1>Editing Affiliate</h1>

<%= render 'form', affiliate: @affiliate %>

<%= link_to 'Show', @affiliate %> |
<%= link_to 'Back', affiliates_path %>

app/views/affiliates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Affiliates</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Logolink</th>
      <th>Moneyconfirmed</th>
        <th>codes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @affiliates.each do |affiliate| %>
      <tr>
        <td><%= affiliate.id %></td>
        <td><%= affiliate.name %></td>
        <td><%= affiliate.logoLink %></td>
        <td><%= affiliate.moneyConfirmed %></td>
        <td><%= affiliate.code %></td>

        <td><p><a href="/affiliates/<%= affiliate.id %>/<%= affiliate.code%>" %>show</a></p></td>
          <td><p><a href="/affiliates/<%= affiliate.id %>/<%= affiliate.code%>/edit" %>edit</a></p></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Affiliate', new_affiliate_path %>

app/views/affiliates/new.html.erb
<h1>New Affiliate</h1>

<%= render 'form', affiliate: @affiliate %>

<%= link_to 'Back', affiliates_path %>

app/views/affiliates/show.html.erb
    
<head>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<header>

</header>      

<header class="main-header">
  <h1><img src="/AFFILIRISKlLOGO.jpg" alt="AFFILIRISKlLOGO" style="height:60px"></h1>
    <nav>
      
    
     
       <ul>
<img src="/<%= @aff%>.png" alt="AFFILIRISKlLOGO" style="height:60px ">
           
<!--      <li><strong>$ CONFIRMED: </strong><%= @M %></li>-->
    </ul>
      
  </nav>
    
</header>
<p></p>
<p></p>
<p></p>

<h2 class="discover"> Discover your no-payment risk </h2 >
 <div style="">
     <p class="ris2
"><a href="#" class="action-button left s0 ris " data-tooltip="U: No enough data">U</a>    <a href="#" class="action-button left s1 ris" data-tooltip="L: There is only a 10% non payment probability.">L</a>
         <a href="#" class="action-button left s2 ris" data-tooltip="M: There is more than 40% of non-payment probability.">M</a>    <a href="#" class="action-button left s3 ris" data-tooltip="H: There is more than 70% of non-payment probability.">H</a>   
         <a href="#" class="action-button left s4 ris" data-tooltip="VH: There is more than 90% of non-payment probability.">V</a>
     </p>
<!--<img src="/Risk.png" alt="AFFILIRISKlLOGO" style="width:30%;height:30%">-->
</div>
<body>
<div class="subBody">    
<table class="container">
  <thead>
    <tr>
      <th>Name</th>
      <th>Installs</th>
      <th>Revenue ($)</th>
      <th>Risk</th>
      <th>Status</th>
      <th>Reason 1</th>
      <th>Reason 2</th>

    </tr>
      
  </thead>
  <tbody>
    <% @offers.each do |request| %>
      <tr>
    <%
      if request.risk==0
        @text="U"
        @textSub="U: No enough data"
      end  
      if request.risk==1
        @text="L"
        @textSub="L: There is only a 10% non payment probability.  "
      end  
      if request.risk==2
        @text="M"
        @textSub="M: There is more than 40% of non-payment probability."
      end  
      if request.risk==3
        @text="H"
        @textSub="H: There is more than 70% of non-payment probability."
      end 
      if request.risk==4
        @text="V"
        @textSub="V: There is more than 90% of non-payment probability"
      end 
    %>
         <%
      if request.finalStatus==0
        @textS="Confirmed"
      end  
      if request.finalStatus==1
        @textS="Hold"
      end  
      if request.finalStatus==2
        @textS="Scrub"
      end  
  
    %>  
        <td><%= request.name %></td>
        <td><%= request.installs %></td>
        <td><%= request.revenue %></td>
        <td>  <a href="#" class="action-button s<%= request.risk %>" data-tooltip="<%= @textSub %>"><%= @text %>  </a>
          </td>

        <td><%= @textS %></tdleft >
        <td><a href="#" class="action-button left s<%= request.risk %>" data-tooltip="<%= request.subComent1 %>"><%= request.comment1 %></a>
</td>
          <td><a href="#" class="action-button left s<%= request.risk %>" data-tooltip="<%= request.subComent2 %>"><%= request.comment2 %></a>
</td>
      </tr>
    <% end %>
  </tbody>
</table>
</p>
<p>.</p>
<p></p>
<p></p>
    
</div>
</body>
<!--<footer>
    <p class="Fott"><strong>Any question or feedback? </strong></p>

        <p class="Fott">Contact your account manager</p>
        <p class="Fott"><i class="fa fa-skype"></i> jorge.campos@doozymob.com</p>
<img src="/madrid.png" alt="AFFILIRISKlLOGO" style="text-aling:center;">
</footer>-->

<footer>
    <p style="text-align:center;"><strong style="text-aling:center; font-size: 15px;">With <i class="fa fa-heart" aria-hidden="true" style="color:red;"></i> for our affiliates</strong></p>
    <hr style="width: 90%;">    
<div id="wrapper">
<div id="footer">
<div class="footerFloat">
<h4><strong>Any question or feedback? </strong></h4>
<pre>Contact your account manager.
<i class="fa fa-skype"></i> jorge.campos@doozymob.com</pre>

</div>
<div class="footerFloat">
<img src="/madrid.gif" alt="AFFILIRISKlLOGO" style="text-aling:center;width:376px;height:110px">
    <hr style="width: 75%;">
    <p class="margina" style="font-size: 10px; text-align: center;"><i class="fa fa-copyright" aria-hidden="true"></i>2017 affilirisk tecnologies all rights reserved to Doozymob</p>
</div>
<div class="footerFloat">

<ul>
<pre class="preFoot">Affilirisk by Doozymob
Discover your no-payment risk</pre>
</ul>
</div>
</div></footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Affilirisk</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/offers/_form.html.erb
<%= form_for(offer) do |f| %>
  <% if offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% offer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

    <div class="field select_create">
      <%= f.label :ownerID %><br>
        <%= f.select(:ownerID) do %>
        <% [['AdsFast','1'],['Appave','2'],['Dobermanmedia','3'],['Doozymob','4'],['Eway','5'],['Flame Digital	','6'],['Iwoop','7'],['Jungletap','8'],['Lollitap','9'],['Mobaloo','10'],['Mobiletraffic','11'],['Mobiplay','12'],['Mobtray','13'],['Mobupps','14'],['Offerseven','15'],['Playbeat','16'],['Rulead','17'],['Smartlead','18'],['Somoto','19'],['Sparklemob','20'],['Spyke Media	','21'],['Stingrad','22'],['Tapgerine','24'],].each do |c| -%>
          <%= content_tag(:option, c.first, value: c.last) %>
        <% end %>
      <% end %>  </div>

  <div class="field">
    <%= f.label :installs %>
    <%= f.text_field :installs %>
  </div>

  <div class="field">
    <%= f.label :revenue  %>
    <%= f.text_field :revenue, :value => 0%>
  </div>

    <div class="field select_create">
      <%= f.label :risk %><br>
        <%= f.select(:risk) do %>
        <% [['U','0'],['L','1'],['M','2'],['H','3'],['VH','4'],].each do |c| -%>
          <%= content_tag(:option, c.first, value: c.last) %>
        <% end %>
      <% end %>  </div>

    <div class="field select_create">
      <%= f.label :finalStatus %><br>
        <%= f.select(:finalStatus) do %>
        <% [['Confirmed','0'],['Hold','1'],['Scrub','2'],].each do |c| -%>
          <%= content_tag(:option, c.first, value: c.last) %>
        <% end %>
      <% end %>  </div>

    <div class="field select_create">
      <%= f.label :comment1 %><br>
        <%= f.select(:comment1) do %>
        <% [['Duplicated IPs','Duplicated IPs'],['RR=0%','RR=0%'],['Traffic Restrictions','Traffic Restrictions'],['High CR','High CR'],['Incent Traffic','Incent Traffic'],['Suspicious installs time','Suspicious installs time'],['Hourly CR','Hourly CR'],['KPI','KPI'],['No in-App Activity','No in-App Activity'],['Click-Spamming','Click-Spamming'],['Time between installs','Time between installs'],['Wrong GEO','Wrong GEO'],['Overcapping','Overcapping'],['No Issues Detected','No Issues Detected'],['KPI issues detected','KPI issues detected'],['KPI accomplished','KPI accomplished'],['Good RR','Good RR'],].each do |c| -%>
          <%= content_tag(:option, c.first, value: c.last) %>
        <% end %>
      <% end %>  </div>



  <div class="field">
    <%= f.label :subComent1 %>
    <%= f.text_field :subComent1 %>
  </div>

    <div class="field select_create">
      <%= f.label :comment12 %><br>
        <%= f.select(:comment2) do %>
        <% [['No Comment',''],['Duplicated IPs','Duplicated IPs'],['RR=0%','RR=0%'],['Traffic Restrictions','Traffic Restrictions'],['High CR','High CR'],['Incent Traffic','Incent Traffic'],['Suspicious installs time','Suspicious installs time'],['Hourly CR','Hourly CR'],['KPI','KPI'],['No in-App Activity','No in-App Activity'],['Click-Spamming','Click-Spamming'],['Time between installs','Time between installs'],['Wrong GEO','Wrong GEO'],['Overcapping','Overcapping'],['No Issues Detected','No Issues Detected'],['KPI issues detected','KPI issues detected'],['KPI accomplished','KPI accomplished'],['Good RR','Good RR'],].each do |c| -%>
          <%= content_tag(:option, c.first, value: c.last) %>
        <% end %>
      <% end %>  </div>



  <div class="field">
    <%= f.label :subComent2 %>
    <%= f.text_field :subComent2 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<h1>Editing Offer</h1>

<%= render 'form', offer: @offer %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

app/views/offers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Offers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ownerid</th>
      <th>Installs</th>
      <th>Revenue</th>
      <th>Risk</th>
      <th>Finalstatus</th>
      <th>Comment1</th>
      <th>Comment2</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= offer.name %></td>
        <td><%= offer.ownerID %></td>
        <td><%= offer.installs %></td>
        <td><%= offer.revenue %></td>
        <td><%= offer.risk %></td>
        <td><%= offer.finalStatus %></td>
        <td><%= offer.comment1 %></td>
        <td><%= offer.comment2 %></td>
        <td><%= link_to 'Show', offer %></td>
        <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
        <td><%= link_to 'Destroy', offer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Offer', new_offer_path %>

app/views/offers/new.html.erb
<div style="text-align:center;">
    <h1>New Offer</h1>
    <%= render 'form', offer: @offer %>
</div>


<%= link_to 'Back', offers_path %>

app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @offer.name %>
</p>

<p>
  <strong>Ownerid:</strong>
  <%= @offer.ownerID %>
</p>

<p>
  <strong>Installs:</strong>
  <%= @offer.installs %>
</p>

<p>
  <strong>Revenue:</strong>
  <%= @offer.revenue %>
</p>

<p>
  <strong>Risk:</strong>
  <%= @offer.risk %>
</p>

<p>
  <strong>Finalstatus:</strong>
  <%= @offer.finalStatus %>
</p>

<p>
  <strong>Comment1:</strong>
  <%= @offer.comment1 %>
</p>

<p>
  <strong>Comment2:</strong>
  <%= @offer.comment2 %>
</p>

<p>
  <strong>SubComment1:</strong>
  <%= @offer.subComent1 %>
</p>

<p>
  <strong>SubComment2:</strong>
  <%= @offer.subComent2 %>
</p>

<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>